**Problem1**

In [1]:
# Task1

array_2x2 = [[None, None], [None, None]]
print(array_2x2)

[[None, None], [None, None]]


In [2]:
# Task2

ones_array = [[1 for _ in range(2)] for _ in range(4)]
print("All Ones Array (4x2)\n:", ones_array)


All Ones Array (4x2)
: [[1, 1], [1, 1], [1, 1], [1, 1]]


In [3]:
# Task3

fill_value = 4
rows, cols = 3, 3
fill_value_array = [[fill_value for _ in range(cols)] for _ in range(rows)]
print("Array Filled with 7 (3x3):\n", fill_value_array)

Array Filled with 7 (3x3):
 [[4, 4, 4], [4, 4, 4], [4, 4, 4]]


In [4]:
# Task4

reference_array = [[5, 6], [7, 8]]
zeros_like_array = [[0 for _ in row] for row in reference_array]
print("Zeros Array with Shape of Reference Array:\n", zeros_like_array)

Zeros Array with Shape of Reference Array:
 [[0, 0], [0, 0]]


In [5]:
# Task5

ones_like_array = [[1 for _ in row] for row in reference_array]
print("Ones Array with Shape of Reference Array:\n", ones_like_array)


Ones Array with Shape of Reference Array:
 [[1, 1], [1, 1]]


In [6]:
# Task6

new_list = [1, 2, 3, 4]
python_array = list(new_list)
print("Converted Array from List:\n", python_array)

Converted Array from List:
 [1, 2, 3, 4]


**Problem2**

In [7]:
# Task1
import numpy as np

array_10_to_49 = np.arange(10, 50)
print("Array from 10 to 49:\n", array_10_to_49)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
# Task2

matrix_0_to_8 = np.arange(9).reshape(3, 3)
print("\n3x3 Matrix from 0 to 8:\n", matrix_0_to_8)


3x3 Matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# Task3

identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# Task4

random_array = np.random.random(30)
mean_value = random_array.mean()
print("\nRandom Array:\n", random_array)
print("Mean of Random Array:", mean_value)


Random Array:
 [7.90378255e-02 3.52590668e-05 5.69408227e-01 8.57132721e-01
 3.35878009e-01 5.07043971e-01 5.16407312e-01 3.58328448e-01
 1.22168343e-01 4.54930159e-02 6.85012708e-01 2.65417967e-01
 1.51487773e-01 7.21503651e-01 4.87933760e-01 2.60886820e-01
 4.21292750e-01 7.72904052e-01 5.43584405e-01 5.95676821e-01
 3.39264466e-01 3.79584861e-01 7.10643099e-01 4.03846458e-01
 9.12109598e-01 2.88786589e-01 6.99108031e-01 6.21544203e-01
 3.73743090e-02 9.45408376e-01]
Mean of Random Array: 0.4544767944411388


In [11]:
# Task5

random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n10x10 Random Array:\n", random_10x10)
print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


10x10 Random Array:
 [[0.10530274 0.4316507  0.35903133 0.11182723 0.74380661 0.67489104
  0.05267383 0.09367658 0.16655823 0.83875229]
 [0.36621088 0.04511487 0.83216914 0.30491897 0.91138527 0.67523817
  0.56425687 0.54609973 0.47372607 0.67649386]
 [0.36350329 0.75732807 0.64466788 0.85284006 0.07575101 0.22654705
  0.2262462  0.35896707 0.24069882 0.88407171]
 [0.9744787  0.71167749 0.06564063 0.02373438 0.9609911  0.73868537
  0.0546818  0.00136334 0.41456967 0.71833885]
 [0.66167867 0.12487619 0.66460924 0.05861864 0.59187702 0.7847278
  0.50369766 0.37188778 0.48994872 0.33411254]
 [0.09825468 0.86961583 0.3254876  0.69339038 0.12941758 0.53942855
  0.5256977  0.55724487 0.56473656 0.4356591 ]
 [0.48626609 0.01276297 0.65381462 0.71033947 0.26295506 0.95546149
  0.67934793 0.52534222 0.86487159 0.87580395]
 [0.70558724 0.24544586 0.94655227 0.4776605  0.62087951 0.54594232
  0.93533261 0.49131584 0.92666559 0.7172292 ]
 [0.84858685 0.43844305 0.33569602 0.04822146 0.59204655 0.

In [12]:
# Task6

zero_array = np.zeros(10)
zero_array[4] = 1
print("\nZero Array with 5th Element as 1:\n", zero_array)


Zero Array with 5th Element as 1:
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [13]:
# Task7

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\nReversed Array:\n", reversed_array)



Reversed Array:
 [0 4 0 0 2 1]


In [14]:
# Task8

bordered_array = np.ones((5, 5))
bordered_array[1:-1, 1:-1] = 0
print("2D Array with Border of 1 and Inside 0:\n", bordered_array)

2D Array with Border of 1 and Inside 0:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
# Q.NO.9

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("8x8 Checkerboard Pattern:\n", checkerboard)

8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**Problem3**

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

In [16]:
# Task1

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
array_addition = x + y
print("Addition of x and y:\n", array_addition)

Addition of x and y:
 [[ 6  8]
 [10 13]]


In [17]:
#Task2

array_subtraction = x - y
print("Subtraction of x and y:\n", array_subtraction)

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]


In [18]:
#Task3

array_multiplication = x * 3
print("Multiplication of x with 3:\n", array_multiplication)

Multiplication of x with 3:
 [[ 3  6]
 [ 9 15]]


In [19]:
#Task4

array_square = x ** 2
print("Square of each element in x:\n", array_square)

Square of each element in x:
 [[ 1  4]
 [ 9 25]]


In [20]:
#Task5

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_product_vw = np.dot(v, w)
dot_product_xv = np.dot(x, v)
dot_product_xy = np.dot(x, y)
print("\nDot product of v and w:", dot_product_vw)
print("Dot product of x and v:\n", dot_product_xv)
print("Dot product of x and y:\n", dot_product_xy)


Dot product of v and w: 219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [21]:
#Task6

concat_xy = np.concatenate((x, y), axis=0)
print("Concatenation of x and y along rows:\n", concat_xy)

# Concatenate v and w along columns
concat_vw = np.vstack((v, w))
print("Concatenation of v and w along columns:\n", concat_vw)


Concatenation of x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenation of v and w along columns:
 [[ 9 10]
 [11 12]]


In [22]:
#Task7

try:
    concat_xv = np.concatenate((x, v), axis=0)
    print("\nConcatenation of x and v:\n", concat_xv)
except ValueError as e:
    print("\nError when concatenating x and v:")
    print(e)


Error when concatenating x and v:
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


**Problem4**

In [23]:
# PART1

import numpy as np

# Define the matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Task 1: Prove A.A^(-1) = I
A_inverse = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inverse)  # A.A^(-1)
print("A.A^(-1):\n", identity_matrix)

is_identity = np.allclose(identity_matrix, np.eye(2))
print("Is A.A^(-1) equal to Identity Matrix (I)?", is_identity)

# Task 2: Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)

is_commutative = np.array_equal(AB, BA)
print("Is AB equal to BA?", is_commutative)

# Task 3: Prove (AB)^T = B^T.A^T
AB_transpose = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)  # B^T . A^T
print("\n(AB)^T:\n", AB_transpose)
print("B^T.A^T:\n", BT_AT)

is_associative = np.allclose(AB_transpose, BT_AT)
print("Is (AB)^T equal to B^T.A^T?", is_associative)

A.A^(-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A.A^(-1) equal to Identity Matrix (I)? True

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Is AB equal to BA? False

(AB)^T:
 [[23 51]
 [13 29]]
B^T.A^T:
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T.A^T? True


In [24]:
# PART2

# Define matrices A and B for the system of equations
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

# Solve using the inverse method: X = A^(-1) * B
A_inverse = np.linalg.inv(A)
X = np.dot(A_inverse, B)

print("Solution to the system of equations (x, y, z):\n", X)

Solution to the system of equations (x, y, z):
 [ 2.  1. -2.]
